config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'users/index'
  end

  root to: 'movies#index'

  # get 'reviews/new'

  # get 'reviews/create'

  # get 'sessions/new'

  # get 'sessions/create'

  # get 'users/new'

  # get 'users/create'

  # get 'movies/index'

  # get 'movies/show'

  # get 'movies/new'

  # get 'movies/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord

  mount_uploader :image, ImageUploader
  
  scope :has_url, -> { where.not(poster_image_url: nil) }

  has_many :reviews

  validates :title, :director, :description, :poster_image_url, :release_date, presence: true
  validates :runtime_in_minutes, numericality: { only_integer: true }

  validate :release_date_is_in_the_past

  def review_average
    reviews.sum(:rating_out_of_ten)/reviews.size unless reviews.size == 0
  end

  def self.search(query1, query2)
    # binding.pry
    if query2 == "1"
      range = (0..89)
    elsif query2 == "2"
      range = (90..120)
    end

    if query2 != ""
      if query2 == "3"
        where('title LIKE :query1 OR director LIKE :query1', query1: "%#{query1}%").where("runtime_in_minutes > ?", 120)
      else
        where('title LIKE :query1 OR director LIKE :query1', query1: "%#{query1}%").where(runtime_in_minutes: range)
      end 
    elsif query2 == ""
      where('title LIKE :query1 OR director LIKE :query1', query1: "%#{query1}%")
    end
  end

  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :user, :movie, :text, presence: true
  validates :rating_out_of_ten, 
             numericality: { 
              only_integer: true, 
              greater_than_or_equal_to: 1, 
              less_than_or_equal_to: 10
             } 
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :reviews, dependent: :destroy

  def full_name
    "#{firstname} #{lastname}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_login
  before_action :check_admin
  
  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.create(user_params)

    @user.admin = true if params[:make_admin] == "1"

    @user.save

    if @user.errors.any?
      render :new
    else
      redirect_to user_path(@user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.admin = true if params[:make_admin] == "1"

    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user == current_user
      flash[:notice] = "You cannot delete yourself"
      redirect_to admin_users_index_path
    else
      UserMailer.delete_email(@user).deliver_later
      @user.destroy
      redirect_to admin_users_index_path
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def check_login
    unless @user = User.find_by(id: session[:user_id])
      flash[:notice] = "You must be logged in"
      redirect_to new_session_path
    end
  end

  def check_admin
    unless @user && @user.admin
      flash[:notice] = "You must be an admin, sneaky bastard!"
      redirect_to new_session_path
    end
  end

  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    # @movies = Movie.all
    # @movies = Movie.has_url
    if params[:search] || params[:runtime_in_minutes]
      @movies = Movie.search(params[:search], params[:runtime_in_minutes])
    else
      @movies = Movie.all
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
     @movie = Movie.create(movie_params)
    if @movie.errors.any?
      render :new
    else
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully"
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])

    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :image
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_movie, :restrict_access

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path
    else
      flash.now[:alert] = "Log in Failed!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    @movies = Movie.all
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id

      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h2>Edit this User</h2>

<%= form_for [:admin, @user] do |f| %>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :firstname%>
    <%= f.text_field :firstname %>
  </div>

  <div>
    <%= f.label :lastname, "Last Name" %>
    <%= f.text_field :lastname %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <% if @user.admin %>
    <p>This User is an Admin</p>
  <% else %>
    <div>
      <%= check_box_tag(:make_admin) %>
      <%= label_tag(:make_admin, "Make This user an admin") %>
    </div>
  <% end %>

  <div>
    <%= f.submit "Submit" %>
  </div>

<% end %>

app/views/admin/users/index.html.erb
<table class="table table-striped">
  <thead>
    <tr><h3>Users List</h3></tr>
    <tr><%= paginate @users %></tr>

    <nav aria-label="...">
      <ul class="pagination pagination-sm">
        <li class="disabled">
          <span>
            <span aria-hidden="true">&laquo;</span>
          </span>
        </li>
        <li class="active">
          <span>1 <span class="sr-only">(current)</span></span>
        </li>
        ...
      </ul>
    </nav>

    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Go To Profile</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.firstname%></td>
      <td><%= user.lastname%></td>
      <td><%= user.email%></td>
      <td><%= link_to "Profile", user_path(user), type:"button", class:"btn btn-primary btn-sm"%></td>
      <td><%= link_to "Edit", edit_admin_user_path(user), type:"button", class:"btn btn-primary btn-sm"%></td>
      <td><%= link_to "Delete", [:admin, user], method: :delete, data: {confirm: "You sure you want to delete #{user.full_name}?"}, type:"button", class:"btn btn-danger btn-sm"%></td>
    </tr>
    <% end %>
  </tbody>
</table>

<hr>
<h3><%= link_to "Create a new User", new_admin_user_path %></h3>

app/views/admin/users/new.html.erb
<h1>Create a New User</h1>

<%= form_for [:admin, @user] do |f| %>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :firstname, "First Name" %>
    <%= f.text_field :firstname %>
  </div>

  <div>
    <%= f.label :lastname, "Last Name" %>
    <%= f.text_field :lastname %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= check_box_tag(:make_admin) %>
    <%= label_tag(:make_admin, "Make This user an admin") %>
  </div>

  <div>
    <%= f.submit "Submit" %>
  </div>

<% end %>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-inverse navbar-default navbar-fixed-bottom">
  <div class="container">
    <% if current_user && current_user.admin? %>
      <%= link_to "GO TO ADMIN PANEL", admin_users_index_path, class:"navbar-btn btn-danger btn pull-right" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RottenMangoes</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <div class="navbar-brand"><strong><%= link_to "Rotten Mangoes", movies_path, class:"brand_heading" %></strong></div>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Log In", new_session_path %></li>
            <li><%= link_to "Sign Up", new_user_path %></li>
            <li><%= link_to "Log Out", session_path("current"), method: :delete %></li>
          </ul>
          <ul class="nav navbar-text navbar-right">
            <% if current_user %>
              <li>Signed in as: <%= current_user.full_name %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div>
          <% flash.each do |key, value| %>
          <%= content_tag(:div, value) %>
          <% end %>
        </div>
      </div>

      <%= yield %>
    
    </div>
    <%= render 'layouts/footer' %> 
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>

  <% if @movie.errors.any? %>
    <div>
        <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
        <ul>
          <% @movie.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :release_date %>
    <%= f.date_field :release_date %>
  </div>

  <div>
    <%= f.label :director %>
    <%= f.text_field :director %>
  </div>

  <div>
    <%= f.label :runtime_in_minutes %>
    <%= f.number_field :runtime_in_minutes %>
  </div>

  <div>
    <%= f.label :poster_image_url %>
    <%= f.text_field :poster_image_url %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.submit "Submit" %>
  </div>

<% end%> 

app/views/movies/_movie.html.erb
<!-- Project One -->

  
  <div class="col-md-6 col-md-offset-2">
    <%= image_tag movie.poster_image_url, class: "center-block img_size img-responsive" %>
  </div>
  <div class="col-md-4">
    <span class="movie_title"><strong><%= movie.title %></strong></span>
    <p><h5><%= formatted_date(movie.release_date) %></h5></p>
    <p><h5>Directed by: <%= movie.director %> </h5></p>
    <p><h6>Runtime: <%= movie.runtime_in_minutes %> minutes</h6></p>
    <%= render partial: 'reviews', locals: { movie: movie }%>
    <div><%= link_to "Details", movie_path(movie), class:"btn btn-primary"%></div>

  </div>
  




<!-- /.row -->







<!-- 
<% if movie.image.thumb.url %>
  <%= image_tag movie.image.thumb.url %>
<% else %>
  <p><small>No thumbnail available</small></p>
<% end%>

<h2><%= link_to movie.title, movie_path(movie) %></h2>
<h3><%= formatted_date(movie.release_date) %></h3>
<h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
<p><%= movie.description %></p> -->

app/views/movies/_reviews.html.erb
<% if movie.review_average %>
  <p class="text-info">Average Rating: <%= movie.review_average %>/10</p>
<% else %>
  <p class="text-info">No available reviews for this movie.. Yet</p>
<% end %>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>

<%= render 'form' %>

app/views/movies/index.html.erb
<%= form_tag movies_path, :method => 'get' do %>
<form class="form-inline">
  <div class="form-group col-md-2">
    <h4>Search for Movies</h4>
  </div>
  <div class="form-group col-md-3">
    <%= text_field_tag :search, params[:search],  class: "form-control", placeholder: "Movie Title or Director" %>
  </div>
  <div class="form-group col-md-3"">
    <%= select_tag "runtime_in_minutes", options_for_select([[""], ["Under 90 minutes",1], ["Between 90 and 120 minutes",2], ["Over 120 minutes",3]], 1), class: "form-control" %>
  </div>
    <%= submit_tag "Search", class: "btn btn-default" %>   
</form>
<% end %>

<hr>

<% if @movies.size > 0 %>
  <% @movies.each do |movie| %>
    <div class="row col-md-6 padding_bottom">
      <%= render partial: 'movie', locals: { movie: movie } %> 
    </div>
  <%end%>
<% elsif @movies.size == 0 %>
  <p>Your search did not return any results</p>
<% end %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>

<%= render 'form' %>






 

app/views/movies/show.html.erb
<%= link_to image_tag(@movie.poster_image_url), movie_path(@movie) %>

<% if @movie.image.thumb.url %>
  <%= image_tag @movie.image.thumb.url %>
<% else %>
  <p><small>No thumbnail available</small></p>
<% end%>

<h2>
  <%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, data: {confirm: "You sure?"} %>)
</h2>

<h3> <%= formatted_date(@movie.release_date) %> </h3>
<h4> Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= link_to review.user.full_name, user_path%></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>

<%= render partial: 'reviews', locals: { movie: @movie } %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>

  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :text %><br>
    <%= f.text_area "text" %>
  </div>

  <div>
    <%= f.label :rating_out_of_ten %><br>
    <%= f.number_field :rating_out_of_ten %>
  </div>

  <div><%= f.submit "Submit" %></div>

<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :firstname, "First Name" %>
    <%= f.text_field :firstname %>
  </div>

  <div>
    <%= f.label :lastname, "Last Name" %>
    <%= f.text_field :lastname %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit "Submit" %>
  </div>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.firstname%>'s Profile</h1>
<hr>
<tr>
  <h4>FullName:</h4><td><%= @user.firstname%></td>
  <td><%= @user.lastname%></td>
  <h4>Email:</h4><p><%= @user.email%></p>
<hr>
  <h3>Movies Reviewed:</h3>
  <% @reviews.each do |review|%>
    <table>
      <tr>
        <td><h4><p><%= link_to review.movie.title, movie_path %>:</p></h4></td>
        <td><p><%=review.text%></p></td>
      </tr>  
    </table>
  <%end%>
</tr>
<hr>

<%= link_to "Back to all movies", movies_path %><br/>